/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.Cidade;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.StaxDriver;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.SwingConstants;
import model.CidadeBusca;
import model.Cidades;

/**
 *
 * @author User
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        mostrarPrevisao(3040);
    }

    Cidades cidadesGlobal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        comboBoxCidades = new javax.swing.JComboBox<>();
        btnBuscaCidade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblData0 = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        lblData3 = new javax.swing.JLabel();
        lblData4 = new javax.swing.JLabel();
        lblData5 = new javax.swing.JLabel();
        lblIcone0 = new javax.swing.JLabel();
        lblIcone1 = new javax.swing.JLabel();
        lblIcone2 = new javax.swing.JLabel();
        lblIcone3 = new javax.swing.JLabel();
        lblIcone4 = new javax.swing.JLabel();
        lblIcone5 = new javax.swing.JLabel();
        lblPrevisao0 = new javax.swing.JLabel();
        lblPrevisao1 = new javax.swing.JLabel();
        lblPrevisao2 = new javax.swing.JLabel();
        lblPrevisao3 = new javax.swing.JLabel();
        lblPrevisao4 = new javax.swing.JLabel();
        lblPrevisao5 = new javax.swing.JLabel();
        lblMax0 = new javax.swing.JLabel();
        lblMax1 = new javax.swing.JLabel();
        lblMax2 = new javax.swing.JLabel();
        lblMax3 = new javax.swing.JLabel();
        lblMax4 = new javax.swing.JLabel();
        lblMax5 = new javax.swing.JLabel();
        lblMin0 = new javax.swing.JLabel();
        lblMin1 = new javax.swing.JLabel();
        lblMin2 = new javax.swing.JLabel();
        lblMin3 = new javax.swing.JLabel();
        lblMin4 = new javax.swing.JLabel();
        lblMin5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bg5 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg0 = new javax.swing.JLabel();
        bg_transl = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquise a cidade desejada:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1030, -1));

        comboBoxCidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCidadesActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, -1));

        btnBuscaCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button.png"))); // NOI18N
        btnBuscaCidade.setBorder(null);
        btnBuscaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscaCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_busca.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblData0.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        lblData0.setForeground(new java.awt.Color(14, 96, 150));
        lblData0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData0.setText("dia e data");
        getContentPane().add(lblData0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 40));

        lblData1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        lblData1.setForeground(new java.awt.Color(14, 96, 150));
        lblData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData1.setText("dia e data");
        getContentPane().add(lblData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 150, 40));

        lblData2.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        lblData2.setForeground(new java.awt.Color(14, 96, 150));
        lblData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData2.setText("dia e data");
        getContentPane().add(lblData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 150, 40));

        lblData3.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        lblData3.setForeground(new java.awt.Color(14, 96, 150));
        lblData3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData3.setText("dia e data");
        getContentPane().add(lblData3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 150, 40));

        lblData4.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        lblData4.setForeground(new java.awt.Color(14, 96, 150));
        lblData4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData4.setText("dia e data");
        getContentPane().add(lblData4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 150, 40));

        lblData5.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        lblData5.setForeground(new java.awt.Color(14, 96, 150));
        lblData5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData5.setText("dia e data");
        getContentPane().add(lblData5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 150, 40));

        lblIcone0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"))); // NOI18N
        getContentPane().add(lblIcone0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 150, 110));

        lblIcone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"))); // NOI18N
        getContentPane().add(lblIcone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 150, 110));

        lblIcone2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"))); // NOI18N
        getContentPane().add(lblIcone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 150, 110));

        lblIcone3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"))); // NOI18N
        getContentPane().add(lblIcone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 150, 110));

        lblIcone4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"))); // NOI18N
        getContentPane().add(lblIcone4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 150, 110));

        lblIcone5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"))); // NOI18N
        getContentPane().add(lblIcone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 150, 110));

        lblPrevisao0.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 18)); // NOI18N
        lblPrevisao0.setForeground(new java.awt.Color(14, 96, 150));
        lblPrevisao0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevisao0.setText("Condicão");
        getContentPane().add(lblPrevisao0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 150, 50));

        lblPrevisao1.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 18)); // NOI18N
        lblPrevisao1.setForeground(new java.awt.Color(14, 96, 150));
        lblPrevisao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevisao1.setText("Condicão");
        getContentPane().add(lblPrevisao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 150, 50));

        lblPrevisao2.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 18)); // NOI18N
        lblPrevisao2.setForeground(new java.awt.Color(14, 96, 150));
        lblPrevisao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevisao2.setText("Condicão");
        getContentPane().add(lblPrevisao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, 50));

        lblPrevisao3.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 18)); // NOI18N
        lblPrevisao3.setForeground(new java.awt.Color(14, 96, 150));
        lblPrevisao3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevisao3.setText("Condicão");
        getContentPane().add(lblPrevisao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 150, 50));

        lblPrevisao4.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 18)); // NOI18N
        lblPrevisao4.setForeground(new java.awt.Color(14, 96, 150));
        lblPrevisao4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevisao4.setText("Condicão");
        getContentPane().add(lblPrevisao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 150, 50));

        lblPrevisao5.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 18)); // NOI18N
        lblPrevisao5.setForeground(new java.awt.Color(14, 96, 150));
        lblPrevisao5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevisao5.setText("Condicão");
        getContentPane().add(lblPrevisao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 150, 50));

        lblMax0.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        lblMax0.setForeground(new java.awt.Color(255, 255, 255));
        lblMax0.setText("00°");
        getContentPane().add(lblMax0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 30));

        lblMax1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 36)); // NOI18N
        lblMax1.setForeground(new java.awt.Color(255, 255, 255));
        lblMax1.setText("01°");
        getContentPane().add(lblMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, 50));

        lblMax2.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 36)); // NOI18N
        lblMax2.setForeground(new java.awt.Color(255, 255, 255));
        lblMax2.setText("01°");
        getContentPane().add(lblMax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 50));

        lblMax3.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 36)); // NOI18N
        lblMax3.setForeground(new java.awt.Color(255, 255, 255));
        lblMax3.setText("01°");
        getContentPane().add(lblMax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, 50));

        lblMax4.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 36)); // NOI18N
        lblMax4.setForeground(new java.awt.Color(255, 255, 255));
        lblMax4.setText("01°");
        getContentPane().add(lblMax4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, 50));

        lblMax5.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 36)); // NOI18N
        lblMax5.setForeground(new java.awt.Color(255, 255, 255));
        lblMax5.setText("01°");
        getContentPane().add(lblMax5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, -1, 50));

        lblMin0.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 36)); // NOI18N
        lblMin0.setForeground(new java.awt.Color(255, 255, 255));
        lblMin0.setText("01°");
        getContentPane().add(lblMin0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 50));

        lblMin1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        lblMin1.setForeground(new java.awt.Color(255, 255, 255));
        lblMin1.setText("00°");
        getContentPane().add(lblMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, 30));

        lblMin2.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        lblMin2.setForeground(new java.awt.Color(255, 255, 255));
        lblMin2.setText("00°");
        getContentPane().add(lblMin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 40, 30));

        lblMin3.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        lblMin3.setForeground(new java.awt.Color(255, 255, 255));
        lblMin3.setText("00°");
        getContentPane().add(lblMin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, 30));

        lblMin4.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        lblMin4.setForeground(new java.awt.Color(255, 255, 255));
        lblMin4.setText("00°");
        getContentPane().add(lblMin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, -1, 30));

        lblMin5.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        lblMin5.setForeground(new java.awt.Color(255, 255, 255));
        lblMin5.setText("00°");
        getContentPane().add(lblMin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_up.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        lblCidade.setFont(new java.awt.Font("GeoSlab703 Md BT", 1, 24)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(14, 96, 150));
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCidade.setText("Local");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1130, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_down.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_down.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_up.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_up.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_up.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_up.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_up.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 470, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_down.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_down.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_down.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_down.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 290, -1, -1));

        bg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_weather.png"))); // NOI18N
        getContentPane().add(bg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, -1, 280));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_weather.png"))); // NOI18N
        getContentPane().add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, 280));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_weather.png"))); // NOI18N
        getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, 280));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_weather.png"))); // NOI18N
        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, 280));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_weather.png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 280));

        bg0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_weather.png"))); // NOI18N
        getContentPane().add(bg0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 280));

        bg_transl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_transl.png"))); // NOI18N
        getContentPane().add(bg_transl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCidadeActionPerformed
        comboBoxCidades.removeAllItems();
        try {
            Cidades cidades = Buscas.buscaCidade(txtBusca.getText().replaceAll(" ", "%20"));
            cidadesGlobal = cidades;
            for (int i = 0; i < cidades.getCidade().size(); i++) {
                comboBoxCidades.addItem(cidades.getCidade().get(i).getNome() + " - "+cidades.getCidade().get(i).getUf());
            }

        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscaCidadeActionPerformed

    private void comboBoxCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCidadesActionPerformed
        try {
            int index = comboBoxCidades.getSelectedIndex();
            mostrarPrevisao(cidadesGlobal.getCidade().get(index).getId());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_comboBoxCidadesActionPerformed

    private void mostrarPrevisao(int IdCidade) {
        Cidade cidade = Buscas.previsao(IdCidade);

        // Definindo os ícones
        lblIcone0.setIcon(getIcon(cidade.getPrevisoes(0).getTempo()));
        lblIcone1.setIcon(getIcon(cidade.getPrevisoes(1).getTempo()));
        lblIcone2.setIcon(getIcon(cidade.getPrevisoes(2).getTempo()));
        lblIcone3.setIcon(getIcon(cidade.getPrevisoes(3).getTempo()));
        lblIcone4.setIcon(getIcon(cidade.getPrevisoes(4).getTempo()));
        lblIcone5.setIcon(getIcon(cidade.getPrevisoes(5).getTempo()));

        // Definindo txt lbl min
        lblMin0.setText(cidade.getPrevisoes(0).getMinima() + "°");
        lblMin1.setText(cidade.getPrevisoes(1).getMinima() + "°");
        lblMin2.setText(cidade.getPrevisoes(2).getMinima() + "°");
        lblMin3.setText(cidade.getPrevisoes(3).getMinima() + "°");
        lblMin4.setText(cidade.getPrevisoes(4).getMinima() + "°");
        lblMin5.setText(cidade.getPrevisoes(5).getMinima() + "°");

        // Definindo txt lbl max
        lblMax0.setText(cidade.getPrevisoes(0).getMaxima() + "°");
        lblMax1.setText(cidade.getPrevisoes(1).getMaxima() + "°");
        lblMax2.setText(cidade.getPrevisoes(2).getMaxima() + "°");
        lblMax3.setText(cidade.getPrevisoes(3).getMaxima() + "°");
        lblMax4.setText(cidade.getPrevisoes(4).getMaxima() + "°");
        lblMax5.setText(cidade.getPrevisoes(5).getMaxima() + "°");

        // Definindo txt lbl previsao
        lblPrevisao0.setText(getDescription(cidade.getPrevisoes(0).getTempo()));
        lblPrevisao1.setText(getDescription(cidade.getPrevisoes(1).getTempo()));
        lblPrevisao2.setText(getDescription(cidade.getPrevisoes(2).getTempo()));
        lblPrevisao3.setText(getDescription(cidade.getPrevisoes(3).getTempo()));
        lblPrevisao4.setText(getDescription(cidade.getPrevisoes(4).getTempo()));
        lblPrevisao5.setText(getDescription(cidade.getPrevisoes(5).getTempo()));

        // Definindo txt lbl data
        lblData0.setText(formatarData(cidade.getPrevisoes(0).getDia()));
        lblData1.setText(formatarData(cidade.getPrevisoes(1).getDia()));
        lblData2.setText(formatarData(cidade.getPrevisoes(2).getDia()));
        lblData3.setText(formatarData(cidade.getPrevisoes(3).getDia()));
        lblData4.setText(formatarData(cidade.getPrevisoes(4).getDia()));
        lblData5.setText(formatarData(cidade.getPrevisoes(5).getDia()));

        // Definindo txt lbl cidade
        lblCidade.setText("Previsão para " + cidade.getNome() + ", " + cidade.getUf());

    }

    public static String getDescription(String code) {
        switch (code) {
            case "ec":
                return "<html><div style='text-align: center;'>Encoberto com<br>Chuvas Isoladas</div></html>";
            case "ci":
                return "<html><div style='text-align: center;'>Chuvas<br>Isoladas</div></html>";
            case "c":
                return "<html><div style='text-align: center;'>Chuva</div></html>";
            case "in":
                return "<html><div style='text-align: center;'>Instável</div></html>";
            case "pp":
                return "<html><div style='text-align: center;'>Possibilidade de<br>Pancadas de Chuva</div></html>";
            case "cm":
                return "<html><div style='text-align: center;'>Chuva<br>pela Manhã</div></html>";
            case "cn":
                return "<html><div style='text-align: center;'>Chuva a<br>Noite</div></html>";
            case "pt":
                return "<html><div style='text-align: center;'>Pancadas de Chuva<br>a Tarde</div></html>";
            case "pm":
                return "<html><div style='text-align: center;'>Pancadas de Chuva<br>pela Manhã</div></html>";
            case "np":
                return "<html><div style='text-align: center;'>Nublado e<br>Pancadas de Chuva</div></html>";
            case "pc":
                return "<html><div style='text-align: center;'>Pancadas de Chuva</div></html>";
            case "pn":
                return "<html><div style='text-align: center;'>Parcialmente<br>Nublado</div></html>";
            case "cv":
                return "<html><div style='text-align: center;'>Chuvisco</div></html>";
            case "ch":
                return "<html><div style='text-align: center;'>Chuvoso</div></html>";
            case "t":
                return "<html><div style='text-align: center;'>Tempestade</div></html>";
            case "ps":
                return "<html><div style='text-align: center;'>Predomínio<br>de Sol</div></html>";
            case "e":
                return "<html><div style='text-align: center;'>Encoberto</div></html>";
            case "n":
                return "<html><div style='text-align: center;'>Nublado</div></html>";
            case "cl":
                return "<html><div style='text-align: center;'>Céu Claro</div></html>";
            case "nv":
                return "<html><div style='text-align: center;'>Nevoeiro</div></html>";
            case "g":
                return "<html><div style='text-align: center;'>Geada</div></html>";
            case "ne":
                return "<html><div style='text-align: center;'>Neve</div></html>";
            case "nd":
                return "<html><div style='text-align: center;'>Não Definido</div></html>";
            case "pnt":
                return "<html><div style='text-align: center;'>Pancadas de<br>Chuva a Noite</div></html>";
            case "psc":
                return "<html><div style='text-align: center;'>Possibilidade<br>de Chuva</div></html>";
            case "pcm":
                return "<html><div style='text-align: center;'>Possibilidade de Chuva<br>pela Manhã</div></html>";
            case "pct":
                return "<html><div style='text-align: center;'>Possibilidade de<br>Chuva a Tarde</div></html>";
            case "pcn":
                return "<html><div style='text-align: center;'>Possibilidade de<br>Chuva a Noite</div></html>";
            case "npt":
                return "<html><div style='text-align: center;'>Nublado com<br>Pancadas a Tarde</div></html>";
            case "npn":
                return "<html><div style='text-align: center;'>Nublado com Pancadas<br>a Noite</div></html>";
            case "ncn":
                return "<html><div style='text-align: center;'>Nublado com<br>Possibilidade de<br>Chuva a Noite</div></html>";
            case "nct":
                return "<html><div style='text-align: center;'>Nublado com<br>Possibilidade de<br>Chuva a Tarde</div></html>";
            case "ncm":
                return "<html><div style='text-align: center;'>Nublado com<br>Possibilidade de<br>Chuva pela Manhã</div></html>";
            case "npm":
                return "<html><div style='text-align: center;'>Nublado com<br>Pancadas<br>pela Manhã</div></html>";
            case "npp":
                return "<html><div style='text-align: center;'>Nublado com<br>Possibilidade<br>de Chuva</div></html>";
            case "vn":
                return "<html><div style='text-align: center;'>Variação de<br>Nebulosidade</div></html>";
            case "ct":
                return "<html><div style='text-align: center;'>Chuva a Tarde</div></html>";
            case "ppn":
                return "<html><div style='text-align: center;'>Possibilidade de<br>Pancadas de<br>Chuva a Noite</div></html>";
            case "ppt":
                return "<html><div style='text-align: center;'>Possibilidade de<br>Pancadas de<br>Chuva a Tarde</div></html>";
            case "ppm":
                return "<html><div style='text-align: center;'>Possibilidade de<br>Pancadas de<br>Chuva pela Manhã</div></html>";
            default:
                return "<html><div style='text-align: center;'>Sem dados</div></html>";
        }
    }

    public ImageIcon getIcon(String code) {
        switch (code) {
            case "ci":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "c":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "in":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/drizzle.png"));
            case "pp":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "cm":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "cn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pt":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pm":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "np":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pc":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/partly_cloudy.png"));
            case "cv":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/drizzle.png"));
            case "ch":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "t":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/stormy.png"));
            case "ps":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/sunny.png"));
            case "e":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/partly_sunny.png"));
            case "n":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/cloudy.png"));
            case "cl":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/sunny.png"));
            case "nv":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/foggy.png"));
            case "g":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/snowy.png"));
            case "ne":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/snowy.png"));
            case "nd":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"));
            case "pnt":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "psc":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pcm":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pct":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "pcn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "npt":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "npn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "ncn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "nct":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "ncm":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "npm":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "npp":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/cloudy.png"));
            case "vn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/foggy.png"));
            case "ct":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            case "ppn":
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/rainy.png"));
            default:
                return new javax.swing.ImageIcon(getClass().getResource("/imagens/undefined.png"));
        }
    }

    private String formatarData(String data) {
        try {
            // Formato de entrada: "2023-08-30"
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            SimpleDateFormat formatoDiaSemana = new SimpleDateFormat("EEEE", new Locale("pt", "BR"));
            SimpleDateFormat formatoDiaMes = new SimpleDateFormat("dd 'de' MMMM", new Locale("pt", "BR"));

            Date dataFormatada = formatoEntrada.parse(data);
            String diaSemana = formatoDiaSemana.format(dataFormatada);
            String diaMes = formatoDiaMes.format(dataFormatada);

            // Retornando o dia da semana e a data em linhas separadas
            return "<html><div style='text-align: center;'>" + diaSemana + "<br>" + diaMes + "</div></html>";
        } catch (Exception e) {
            e.printStackTrace();
            return "Data inválida";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg0;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg5;
    private javax.swing.JLabel bg_transl;
    private javax.swing.JButton btnBuscaCidade;
    private javax.swing.JComboBox<String> comboBoxCidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblData0;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblData3;
    private javax.swing.JLabel lblData4;
    private javax.swing.JLabel lblData5;
    private javax.swing.JLabel lblIcone0;
    private javax.swing.JLabel lblIcone1;
    private javax.swing.JLabel lblIcone2;
    private javax.swing.JLabel lblIcone3;
    private javax.swing.JLabel lblIcone4;
    private javax.swing.JLabel lblIcone5;
    private javax.swing.JLabel lblMax0;
    private javax.swing.JLabel lblMax1;
    private javax.swing.JLabel lblMax2;
    private javax.swing.JLabel lblMax3;
    private javax.swing.JLabel lblMax4;
    private javax.swing.JLabel lblMax5;
    private javax.swing.JLabel lblMin0;
    private javax.swing.JLabel lblMin1;
    private javax.swing.JLabel lblMin2;
    private javax.swing.JLabel lblMin3;
    private javax.swing.JLabel lblMin4;
    private javax.swing.JLabel lblMin5;
    private javax.swing.JLabel lblPrevisao0;
    private javax.swing.JLabel lblPrevisao1;
    private javax.swing.JLabel lblPrevisao2;
    private javax.swing.JLabel lblPrevisao3;
    private javax.swing.JLabel lblPrevisao4;
    private javax.swing.JLabel lblPrevisao5;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
